//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrinterPSTDrivesList.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrinterPSTDrivesList.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Aha_Soft_Universal_Shop_Print {
            get {
                object obj = ResourceManager.GetObject("Aha_Soft_Universal_Shop_Print", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nyan_CatSmall {
            get {
                object obj = ResourceManager.GetObject("Nyan_CatSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLNPTR08:OANC002PR;OLNPTR10:OANC003PR;OLNPTR11:OANC004PR;OLNPTR12:OANC005PR;OLNPTR13:OANC006PR;OLNPTR29:OANC007PR;OLNPTR36:OANC008PR;OLNPTR39:OANC009PR;OLNPTR40:OANC010PR;OLNPLOT47:OANC011PL;OLNPLOT48:OANC012PL;OLNPTR51:OANC013PR;OLNPTR54:OANC014PR;OLNPTR82:OANC015PR;OLNPTR87:OANC016PR;OLNPTR98:OANC017PR;OLNPTR103:OANC018PR;OLNPTR107:OANC019PR;OLNPTR125:OANC020PR;OLNPTR133:OANC021PR;OLNPTR301:OANC022PR;OLNPTR302:OANC023PR;OLNPTR304:OANC024PR;OLNPTR306:OANC025PR;OLNPTR308:OANC026PR;OLNPTR309:OANC027PR;OLNPTR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OleanPrintersNew {
            get {
                return ResourceManager.GetString("OleanPrintersNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OANC002PR,OANC003PR,OANC004PR,OANC005PR,OANC006PR,OANC007PR,OANC008PR,OANC009PR,OANC010PR,OANC011PL,OANC012PL,OANC013PR,OANC014PR,OANC015PR,OANC016PR,OANC017PR,OANC018PR,OANC019PR,OANC020PR,OANC021PR,OANC022PR,OANC023PR,OANC024PR,OANC025PR,OANC026PR,OANC027PR,OANC028PR,OANC029PR,OANC030PR,OANC031PR,OANC032PR,OANC033PR,OANC034PR,OANC035PR,OANC036PR,OANC037PR,OANC038PL,OANC039PR,OANC040PR,OANC041PR,OANC042PR,OANC043PR,OANC044PR,OANC045PR,OANC046PR,OANC047PR,OANC048PR,OANC049PR,OANC050PR,OANC051PR,OANC052PR,OA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OleanPrintersNEW2 {
            get {
                return ResourceManager.GetString("OleanPrintersNEW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLNPTR08,OLNPTR10,OLNPTR11,OLNPTR12,OLNPTR13,OLNPTR29,OLNPTR36,OLNPTR39,OLNPTR40,OLNPLOT47,OLNPLOT48,OLNPTR51,OLNPTR54,OLNPTR82,OLNPTR87,OLNPTR98,OLNPTR103,OLNPTR107,OLNPTR125,OLNPTR133,OLNPTR301,OLNPTR302,OLNPTR304,OLNPTR306,OLNPTR308,OLNPTR309,OLNPTR211,OLNPTR310,OLNPTR311,OLNPTR312,OLNPTR313,OLNPTR314,OLNPTR315,OLNPTR316,OLNPTR215,OLNPTR219,OLNPLOT232,OLNPTR233,OLNPTR250,OLNPTR251,OLNPTR252,OLNPTR253,OLNPTR254,OLNPTR255,OLNPTR256,OLNPTR257,OLNPTR258,OLNPTR259,OLNPTR260,OLNPTR264,OLNPTR265,OLNPTR266,OLNPT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OleanPrintersOLD2 {
            get {
                return ResourceManager.GetString("OleanPrintersOLD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] outlook_store {
            get {
                object obj = ResourceManager.GetObject("outlook_store", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##
        ///# Begin Script
        ///##
        ///
        ///# Create Outlook object
        ///$Outlook = New-Object -ComObject Outlook.Application
        ///$stores = $Outlook.Session.Stores
        ///$accounts = $outlook.session.accounts
        ///
        ///# Basic information
        ///&quot;Current profile has the following configured accounts:&quot;
        ///$dn = @{label = &quot;Account Type&quot;; expression={$_.displayname}}
        ///$un = @{label = &quot;User Name&quot;; expression = {$_.username}}
        ///$sm = @{label = &quot;SMTP Address&quot;; expression = {$_.smtpaddress}}
        ///$accounts | Format-Table -AutoSize $dn,$un,$sm
        ///
        ///# Check number of  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string outlook_store2_ps1 {
            get {
                return ResourceManager.GetString("outlook_store2_ps1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PrinterDrivesPST {
            get {
                object obj = ResourceManager.GetObject("PrinterDrivesPST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADOBE PDF;BRLW098PR;BRLW099PR;BRLW100PR;BRLW101PR;BRLW102PR;BRLW103PR;BRLW104PR;BRLW105PR;BRLW106PR;BRLW107PR;BRLW108PR;BRLW109PR;BRLW110PR;BRLW111PR;BRLW112PR;BTRD170PR;BTRD172PR;CCHPTR64;CCRCC14PR;CRNGS146PR;CRNGS147PR;FAFS018PR;FCUM034PR;FCUM035PR;FCUM036PR;FCUM037PR;HOUPTR01;HOUPTR05;HOUPTR09;HOUPTR11;HOUPT141;HOUPTR51;HOUPTR52;HOUPTR53;HOUPTR54;HOUPTR55;HOUPTR56;HOUPTR57;HOUPTR58;HOUPTR63;HOUPTR65;HOUPTR69;HOUPTR72;HOUPTR73;HOUPTR76;HOUPTR77;HOUPTR78;HOUPTR79;HOUPTR80;HOUPTR81;HOUPTR82;HOUPTR83;HOUPTR8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string printers {
            get {
                return ResourceManager.GetString("printers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OANC002PR;OANC003PR;OANC004PR;OANC005PR;OANC006PR;OANC007PR;OANC008PR;OANC009PR;OANC010PR;OANC011PL;OANC012PL;OANC013PR;OANC014PR;OANC015PR;OANC016PR;OANC017PR;OANC018PR;OANC019PR;OANC020PR;OANC021PR;OANC022PR;OANC023PR;OANC024PR;OANC025PR;OANC026PR;OANC027PR;OANC028PR;OANC029PR;OANC030PR;OANC031PR;OANC032PR;OANC033PR;OANC034PR;OANC035PR;OANC036PR;OANC037PR;OANC038PL;OANC039PR;OANC040PR;OANC041PR;OANC042PR;OANC043PR;OANC044PR;OANC045PR;OANC046PR;OANC047PR;OANC048PR;OANC049PR;OANC050PR;OANC051PR;OANC052PR;OA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string printersOlean {
            get {
                return ResourceManager.GetString("printersOlean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPTPTR102;PPTPTR102X;PPTPTR104;PPTPTR105;PPTPTR113;PPTPTR115;PPTPTR116;PPTPTR116_2;PPTPTR117;PPTPTR118;PPTPTR119;PPTPTR119X;PPTPTR120X;PPTPTR121;PPTPTR121X;PPTPTR122X;PPTPTR123;PPTPTR124X;PPTPTR124X_1;PPTPTR124X_2;PPTPTR125;PPTPTR125X;PPTPTR126X;PPTPTR127X;PPTPTR12;PPTPTR128X;PPTPTR129X;PPTPTR130;PPTPTR131X;PPTPTR135;PPTPTR136;PPTPTR138;PPTPTR140;PPTPTR142;PPTPTR144;PPTPTR145;PPTPTR147;PPTPTR148;PPTPTR150;PPTPTR155;PPTPTR155W;PPTPTR158;PPTPTR160;PPTPTR161W;PPTPTR162;PPTPTR163W;PPTPTR165;PPTPTR169;PPTPTR170; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string printersPPT {
            get {
                return ResourceManager.GetString("printersPPT", resourceCulture);
            }
        }
    }
}
